version: '3.8'

# Ultra-minimal single-service configuration for Coolify
# This eliminates any multi-service complexity that might confuse SSL generation

services:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"