version: '3.8'

services:
  backend:
    build:
      context: ./web_dashboard/backend
      dockerfile: Dockerfile
    container_name: cowans-backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:////app/data/database.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - SHOPIFY_SHOP_URL=${SHOPIFY_SHOP_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FTP_HOST=${FTP_HOST}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - PYTHONUNBUFFERED=1
    volumes:
      - backend-data:/app/data
      - shared-icons:/app/icons
      - ./data:/app/import-data:ro
    ports:
      - "3560:3560"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3560/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cowans-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost/api}
    container_name: cowans-frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost/api}
    ports:
      - "3055:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - cowans-network

  celery:
    build:
      context: ./web_dashboard/backend
      dockerfile: Dockerfile
    container_name: cowans-celery
    command: celery -A celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=sqlite:////app/data/database.db
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379/0}
      - SHOPIFY_SHOP_URL=${SHOPIFY_SHOP_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - backend-data:/app/data
      - shared-icons:/app/icons
      - ./data:/app/import-data:ro
    depends_on:
      - backend
      - redis
    restart: unless-stopped
    networks:
      - cowans-network

  redis:
    image: redis:7-alpine
    container_name: cowans-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - cowans-network

  nginx:
    image: nginx:alpine
    container_name: cowans-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - shared-icons:/usr/share/nginx/html/icons:ro
      - nginx-certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - cowans-network

volumes:
  backend-data:
    driver: local
  shared-icons:
    driver: local
  redis-data:
    driver: local
  nginx-certs:
    driver: local

networks:
  cowans-network:
    driver: bridge