services:
  backend:
    build:
      context: .
      dockerfile: ./web_dashboard/backend/Dockerfile
    container_name: cowans-backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://postgres.gqozcvqgsjaagnnjukmo:fotMat-gomqih-8cybne@aws-0-us-west-1.pooler.supabase.com:6543/postgres}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_USE_POOLER=true
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - SHOPIFY_SHOP_URL=${SHOPIFY_SHOP_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FTP_HOST=${FTP_HOST}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - PYTHONUNBUFFERED=1
      # Performance tuning for small server
      - GUNICORN_WORKERS=1  # 1 worker for 2 CPUs
      - GUNICORN_WORKER_CONNECTIONS=50  # Reduced from 500
      - GUNICORN_THREADS=2  # Use threads instead of processes
      - MEMORY_MONITOR_ENABLED=false  # Disable memory monitoring in prod
    volumes:
      - backend-data:/app/data
      - shared-icons:/app/icons
      - ./data:/app/import-data:ro
    ports:
      - "3560:3560"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3560/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - cowans-network
    # Resource limits for 2CPU/4GB server
    deploy:
      resources:
        limits:
          cpus: '0.8'  # 80% of 1 CPU for backend
          memory: 1G    # 1GB RAM max
        reservations:
          cpus: '0.5'  # Guarantee 50% of 1 CPU
          memory: 512M  # Guarantee 512MB RAM

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost/api}
    container_name: cowans-frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost/api}
    ports:
      - "3055:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - cowans-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.3'  # 30% of 1 CPU for static files
          memory: 256M  # 256MB RAM max
        reservations:
          cpus: '0.1'  # Guarantee 10% of 1 CPU
          memory: 128M  # Guarantee 128MB RAM

  celery:
    build:
      context: .
      dockerfile: ./web_dashboard/backend/Dockerfile
    container_name: cowans-celery
    command: celery -A celery_app worker --loglevel=info --concurrency=1 --max-tasks-per-child=100
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg://postgres.gqozcvqgsjaagnnjukmo:fotMat-gomqih-8cybne@aws-0-us-west-1.pooler.supabase.com:6543/postgres}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_USE_POOLER=true
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SHOPIFY_SHOP_URL=${SHOPIFY_SHOP_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MEMORY_MONITOR_ENABLED=false
    volumes:
      - backend-data:/app/data
      - shared-icons:/app/icons
      - ./data:/app/import-data:ro
    depends_on:
      - backend
      - redis
    restart: unless-stopped
    networks:
      - cowans-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'  # 50% of 1 CPU for Celery
          memory: 768M  # 768MB RAM max
        reservations:
          cpus: '0.3'  # Guarantee 30% of 1 CPU
          memory: 512M  # Guarantee 512MB RAM

  redis:
    image: redis:7-alpine
    container_name: cowans-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - cowans-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.2'  # 20% of 1 CPU for Redis
          memory: 256M  # 256MB RAM max
        reservations:
          cpus: '0.1'  # Guarantee 10% of 1 CPU
          memory: 128M  # Guarantee 128MB RAM
    # Redis memory policy for small servers
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru

  nginx:
    image: nginx:alpine
    container_name: cowans-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - shared-icons:/usr/share/nginx/html/icons:ro
      - nginx-certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - cowans-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.2'  # 20% of 1 CPU for Nginx
          memory: 128M  # 128MB RAM max
        reservations:
          cpus: '0.1'  # Guarantee 10% of 1 CPU
          memory: 64M   # Guarantee 64MB RAM

volumes:
  backend-data:
    driver: local
  shared-icons:
    driver: local
  redis-data:
    driver: local
  nginx-certs:
    driver: local

networks:
  cowans-network:
    driver: bridge