version: '3.8'

# Coolify v4 optimized configuration  
# This compose file is specifically designed for Coolify deployment
# IMPORTANT: Frontend service MUST be first to get the domain assignment

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=/api
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/api
    expose:
      - "80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=frontend"
      - "coolify.port=80"
      - "coolify.domain=${COOLIFY_URL:-cowans.apps.iaminawe.net}"
      - "coolify.https=true"

  backend:
    build:
      context: .
      dockerfile: ./web_dashboard/backend/Dockerfile
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SHOPIFY_SHOP_URL=${SHOPIFY_SHOP_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FTP_HOST=${FTP_HOST}
      - FTP_USERNAME=${FTP_USERNAME}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    volumes:
      - backend-data:/app/data
      - shared-icons:/app/icons
    expose:
      - "3560"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3560/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "coolify.type=database"

  celery:
    build:
      context: .
      dockerfile: ./web_dashboard/backend/Dockerfile
    command: celery -A celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SHOPIFY_SHOP_URL=${SHOPIFY_SHOP_URL}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - backend-data:/app/data
      - shared-icons:/app/icons
    depends_on:
      - backend
      - redis
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "coolify.type=worker"

volumes:
  backend-data:
    driver: local
  shared-icons:
    driver: local
  redis-data:
    driver: local